name: Pull Request Alert
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    name: Chat Bot
    runs-on: ubuntu-latest
    steps:
    - name: Send chat message
      run: |
        curl -sS --output /dev/null -X POST -H 'Content-Type: application/json' "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" -d '{"text": "Please Review and Merge - ${{ github.event.pull_request.html_url }} "}' || echo "Sending PR alerts failed"
